// <auto-generated />
using System;
using LumenHut.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumenHut.Data.Migrations
{
    [DbContext(typeof(PerfDbContext))]
    [Migration("20260821200447_AddTimestampIndex")]
    partial class AddTimestampIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LumenHut.Models.BrowserResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkipReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestRunId");

                    b.ToTable("BrowserResults");
                });

            modelBuilder.Entity("LumenHut.Models.PerformanceMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrowserResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BrowserResultId");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("LumenHut.Models.TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProxyUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Viewport")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("LumenHut.Models.BrowserResult", b =>
                {
                    b.HasOne("LumenHut.Models.TestRun", "TestRun")
                        .WithMany("BrowserResults")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("LumenHut.Models.PerformanceMetric", b =>
                {
                    b.HasOne("LumenHut.Models.BrowserResult", "BrowserResult")
                        .WithMany("Metrics")
                        .HasForeignKey("BrowserResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrowserResult");
                });

            modelBuilder.Entity("LumenHut.Models.BrowserResult", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("LumenHut.Models.TestRun", b =>
                {
                    b.Navigation("BrowserResults");
                });
#pragma warning restore 612, 618
        }
    }
}
